services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    working_dir: /app
